/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikum12;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LENOVO
 */
public class menu extends javax.swing.JFrame {

    public Connection conn;
    public Statement cn;

    /**
     * Creates new form menu
     */
    public void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbakademik2222001", "root", "");
            cn = conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "koneksi gagal..");
            System.out.println(e.getMessage());
        }
    }

    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        inputmhs = new javax.swing.JMenuItem();
        inputmatkul = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        entrikrs = new javax.swing.JMenuItem();
        entrinilai = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        lmatkul = new javax.swing.JMenuItem();
        lmhs = new javax.swing.JMenuItem();
        lnilai = new javax.swing.JMenuItem();
        LHS = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        User = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        inputmhs.setText("Mahasiswa");
        inputmhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputmhsActionPerformed(evt);
            }
        });
        jMenu1.add(inputmhs);

        inputmatkul.setText("Matakuliah");
        inputmatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputmatkulActionPerformed(evt);
            }
        });
        jMenu1.add(inputmatkul);

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Proses");

        entrikrs.setText("Entri KRS");
        entrikrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrikrsActionPerformed(evt);
            }
        });
        jMenu2.add(entrikrs);

        entrinilai.setText("Entri Nilai");
        jMenu2.add(entrinilai);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cetak");

        lmatkul.setText("Laporan Matakuliah");
        lmatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lmatkulActionPerformed(evt);
            }
        });
        jMenu3.add(lmatkul);

        lmhs.setText("Laporan Mahasiswa");
        lmhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lmhsActionPerformed(evt);
            }
        });
        jMenu3.add(lmhs);

        lnilai.setText("Laporan Nilai");
        jMenu3.add(lnilai);

        LHS.setText("Laporan Hasil Studi(LHS)");
        jMenu3.add(LHS);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Setting");

        User.setText("User");
        jMenu4.add(User);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputmhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputmhsActionPerformed
        // TODO add your handling code here:
        new mahasiswa().show();
    }//GEN-LAST:event_inputmhsActionPerformed

    private void inputmatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputmatkulActionPerformed
        // TODO add your handling code here:
        new matakuliah().show();
    }//GEN-LAST:event_inputmatkulActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_logoutActionPerformed

    private void lmatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lmatkulActionPerformed
        // TODO add your handling code here:
        try {
            HashMap parameter = new HashMap();
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql:" + "///dbakademik2222001", "root", "");
            String sql = "SELECT * FROM matakuliah2222001";
            File file = new File("src/LaporanPraktikum12/laporanmtk.jasper");
            JasperReport jr = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, cn);
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Data Tidak Dapat di Cetak !!!" + "\n" + e.getMessage(), "Cetak Data", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lmatkulActionPerformed

    private void lmhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lmhsActionPerformed
        // TODO add your handling code here:
        try {
            HashMap parameter = new HashMap();
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql:" + "///dbakademik2222001", "root", "");
            String sql = "SELECT * FROM mahasiswa2222001";
            File file = new File("src/LaporanPraktikum12/laporanmhs.jasper");
            JasperReport jr = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, cn);
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Data Tidak Dapat di Cetak !!!" + "\n" + e.getMessage(), "Cetak Data", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lmhsActionPerformed

    private void entrikrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrikrsActionPerformed
        // TODO add your handling code here:
        new krs().show();
    }//GEN-LAST:event_entrikrsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LHS;
    private javax.swing.JMenuItem User;
    private javax.swing.JMenuItem entrikrs;
    private javax.swing.JMenuItem entrinilai;
    private javax.swing.JMenuItem inputmatkul;
    private javax.swing.JMenuItem inputmhs;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem lmatkul;
    private javax.swing.JMenuItem lmhs;
    private javax.swing.JMenuItem lnilai;
    private javax.swing.JMenuItem logout;
    // End of variables declaration//GEN-END:variables
}
